/**
 * ============================================================================
 * SIDEBAR PRESETS DATA
 * ============================================================================
 * Contient toutes les configurations de cuisines pré-construites.
 */

export const PRESETS = {
	lineaire: {
		items: (defaultConfig) => [
			{
				id: crypto.randomUUID(),
				type: "window",
				position: [900, 900, -1450],
				dimensions: { width: 1000, height: 1000, depth: 100 },
				rotation: 0,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "tall_cabinet",
				position: [-900, 0, -1200],
				dimensions: { width: 600, height: 2100, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "oven_microwave" },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [-300, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, isTiroirsInterieurs: true },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [300, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "cooktop" },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [900, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "sink" },
			},
			{
				id: crypto.randomUUID(),
				type: "wall_cabinet",
				position: [-300, 1400, -1325],
				dimensions: { width: 600, height: 700, depth: 350 },
				rotation: 0,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "wall_cabinet",
				position: [300, 1400, -1325],
				dimensions: { width: 600, height: 700, depth: 350 },
				rotation: 0,
				config: defaultConfig,
			},
		],
	},
	L: {
		items: (defaultConfig) => [
			{
				id: crypto.randomUUID(),
				type: "window",
				position: [-1950, 900, -600],
				dimensions: { width: 1000, height: 1000, depth: 100 },
				rotation: 90,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [-1700, 0, -600],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 270,
				config: { ...defaultConfig, equipement: "sink" },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [-1700, 0, 0],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 270,
				config: { ...defaultConfig, isTiroirsInterieurs: true },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [-1100, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "cooktop" },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [-500, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "tall_cabinet",
				position: [100, 0, -1200],
				dimensions: { width: 600, height: 2100, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "oven_microwave" },
			},
		],
	},
	U: {
		items: (defaultConfig) => [
			{
				id: crypto.randomUUID(),
				type: "window",
				position: [100, 900, -1450],
				dimensions: { width: 1000, height: 1000, depth: 100 },
				rotation: 0,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [-1700, 0, 0],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 270,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [-1700, 0, 600],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 270,
				config: { ...defaultConfig, equipement: "sink" },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [-1100, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, isTiroirsInterieurs: true },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [-500, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [100, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [700, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "cooktop" },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [1700, 0, 0],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 90,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "tall_cabinet",
				position: [1700, 0, 600],
				dimensions: { width: 600, height: 2100, depth: 600 },
				rotation: 90,
				config: { ...defaultConfig, equipement: "oven_microwave" },
			},
		],
	},
	ilot: {
		items: (defaultConfig) => [
			{
				id: crypto.randomUUID(),
				type: "window",
				position: [600, 900, -1450],
				dimensions: { width: 1000, height: 1000, depth: 100 },
				rotation: 0,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "tall_cabinet",
				position: [-1200, 0, -1200],
				dimensions: { width: 600, height: 2100, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "oven_microwave" },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [-600, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, isTiroirsInterieurs: true },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [0, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "cooktop" },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [600, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "tall_cabinet",
				position: [1200, 0, -1200],
				dimensions: { width: 600, height: 2100, depth: 600 },
				rotation: 0,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "island",
				position: [0, 0, 200],
				dimensions: { width: 1800, height: 900, depth: 900 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "sink" },
			},
		],
	},
	parallele: {
		items: (defaultConfig) => [
			{
				id: crypto.randomUUID(),
				type: "window",
				position: [0, 900, -1450],
				dimensions: { width: 1000, height: 1000, depth: 100 },
				rotation: 0,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [-600, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, isTiroirsInterieurs: true },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [0, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "cooktop" },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [600, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [-600, 0, 0],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 180,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [0, 0, 0],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 180,
				config: { ...defaultConfig, equipement: "sink" },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [600, 0, 0],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 180,
				config: { ...defaultConfig, isTiroirsInterieurs: true },
			},
		],
	},
	studio: {
		items: (defaultConfig) => [
			{
				id: crypto.randomUUID(),
				type: "tall_cabinet",
				position: [-600, 0, -1200],
				dimensions: { width: 600, height: 2100, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "oven_microwave" },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [0, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "sink" },
			},
			{
				id: crypto.randomUUID(),
				type: "base_cabinet",
				position: [600, 0, -1200],
				dimensions: { width: 600, height: 812, depth: 600 },
				rotation: 0,
				config: { ...defaultConfig, equipement: "cooktop" },
			},
			{
				id: crypto.randomUUID(),
				type: "wall_cabinet",
				position: [0, 1400, -1325],
				dimensions: { width: 600, height: 700, depth: 350 },
				rotation: 0,
				config: defaultConfig,
			},
			{
				id: crypto.randomUUID(),
				type: "wall_cabinet",
				position: [600, 1400, -1325],
				dimensions: { width: 600, height: 700, depth: 350 },
				rotation: 0,
				config: defaultConfig,
			},
		],
	},
};
