/**
 * ============================================================================
 * THEME - Styles de l'interface utilisateur
 * ============================================================================
 * Ce fichier centralise tous les styles CSS-in-JS pour le configurateur.
 * Utilisé par les composants Sidebar, QuoteBox et BottomBar.
 */

export const theme = {
  panel: {
    width: "360px",
    background: "#ffffff",
    borderRight: "1px solid #e5e7eb",
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    fontFamily: "'Inter', sans-serif",
    zIndex: 10,
    boxShadow: "4px 0 24px rgba(0,0,0,0.02)",
  },
  header: { padding: "24px 24px 20px", borderBottom: "1px solid #f3f4f6", backgroundColor: "#ffffff" },
  titleH1: { margin: 0, fontSize: "22px", fontWeight: "700", color: "#111827", letterSpacing: "-0.02em" },
  subtitle: { margin: "6px 0 0 0", fontSize: "13px", color: "#6b7280" },
  scrollArea: { flex: 1, overflowY: "auto", padding: "24px", display: "flex", flexDirection: "column", gap: "32px" },
  section: { display: "flex", flexDirection: "column", gap: "16px" },
  sectionHeader: { display: "flex", alignItems: "center", gap: "8px", borderBottom: "2px solid #f8fafc", paddingBottom: "10px" },
  sectionTitle: { margin: 0, fontSize: "12px", fontWeight: "700", textTransform: "uppercase", letterSpacing: "0.05em", color: "#111827" },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" },
  inputGroup: { display: "flex", flexDirection: "column", gap: "8px" },

  sliderHeader: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  label: { fontSize: "13px", fontWeight: "600", color: "#374151", margin: 0 },
  valueBadge: { fontSize: "12px", fontWeight: "700", color: "#111827", backgroundColor: "#f3f4f6", padding: "4px 8px", borderRadius: "6px" },
  slider: { width: "100%", cursor: "pointer", accentColor: "#111827" },

  input: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
    fontSize: "14px",
    color: "#111827",
    backgroundColor: "#f9fafb",
    boxSizing: "border-box",
    outline: "none",
  },
  select: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
    fontSize: "14px",
    color: "#111827",
    backgroundColor: "#f9fafb",
    cursor: "pointer",
    boxSizing: "border-box",
    outline: "none",
  },
  btnPrimary: {
    width: "100%",
    padding: "14px",
    background: "#111827",
    color: "#ffffff",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    display: "block",
    textAlign: "center",
    textDecoration: "none",
    boxSizing: "border-box",
    boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1)",
    transition: "background 0.2s",
  },
  btnSecondary: {
    width: "100%",
    padding: "12px 10px",
    background: "#ffffff",
    color: "#111827",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "8px",
    boxSizing: "border-box",
    transition: "all 0.2s",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
  },
  colorPickerWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "8px 12px",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
    background: "#f9fafb",
  },
  colorPicker: { width: "24px", height: "24px", border: "none", cursor: "pointer", background: "none", padding: 0 },
  checkboxWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "10px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    cursor: "pointer",
    background: "#f9fafb",
  },
  checkbox: { width: "16px", height: "16px", accentColor: "#111827", cursor: "pointer", margin: 0 },

  quoteBox: {
    position: "absolute",
    top: "24px",
    right: "24px",
    backgroundColor: "#ffffff",
    padding: "24px",
    borderRadius: "16px",
    boxShadow: "0 20px 25px -5px rgba(0,0,0,0.1), 0 8px 10px -6px rgba(0,0,0,0.1)",
    zIndex: 100,
    border: "1px solid #e5e7eb",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    minWidth: "240px",
    fontFamily: "'Inter', sans-serif",
  },
  quotePrice: { margin: 0, fontSize: "36px", fontWeight: "800", color: "#111827", letterSpacing: "-0.03em" },
  quoteLabel: { margin: "0 0 4px 0", fontSize: "12px", fontWeight: "700", color: "#6b7280", textTransform: "uppercase", letterSpacing: "0.05em" },

  bottomBar: {
    position: "absolute",
    bottom: "32px",
    left: "50%",
    transform: "translateX(-50%)",
    backgroundColor: "#ffffff",
    padding: "20px 32px",
    borderRadius: "16px",
    boxShadow: "0 25px 50px -12px rgba(0,0,0,0.25)",
    display: "flex",
    gap: "32px",
    alignItems: "flex-end",
    zIndex: 100,
    border: "1px solid #e5e7eb",
  },
  bottomBarSection: { display: "flex", flexDirection: "column", gap: "10px", borderRight: "1px solid #e5e7eb", paddingRight: "32px" },
};

export default theme;
