/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 meuble.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/meuble.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.001}>
          <group position={[2823.882, 232.837, 0]} scale={25.4}>
            <mesh geometry={nodes.Geom3D_tiroir2.geometry} material={nodes.Geom3D_tiroir2.material} />
            <mesh geometry={nodes.Geom3D_.geometry} material={nodes.Geom3D_.material} />
            <mesh geometry={nodes.Geom3D__1.geometry} material={nodes.Geom3D__1.material} position={[0, 0.709, 0]} />
            <mesh geometry={nodes.Geom3D__2.geometry} material={nodes.Geom3D__2.material} position={[21.102, 23.937, 15.669]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
            <mesh geometry={nodes.Geom3D_Différence.geometry} material={nodes.Geom3D_Différence.material} position={[21.811, 0.709, 0.709]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Geom3D_Différence_1.geometry} material={nodes.Geom3D_Différence_1.material} position={[0.709, 0.709, 0.709]} rotation={[0, -1.571, 0]} />
          </group>
          <group position={[954.226, 10, 289.325]} scale={25.4}>
            <mesh geometry={nodes.Geom3D_tiroir_porte.geometry} material={nodes.Geom3D_tiroir_porte.material} position={[4.811, 10.836, 0]} />
            <mesh geometry={nodes.Geom3D_tiroir_bas.geometry} material={nodes.Geom3D_tiroir_bas.material} />
            <mesh geometry={nodes.Geom3D_tiroir_fond_arrière.geometry} material={nodes.Geom3D_tiroir_fond_arrière.material} position={[2.574, 16.61, 0]} />
            <mesh geometry={nodes.Geom3D_Différence_2.geometry} material={nodes.Geom3D_Différence_2.material} position={[0, -0.394, 0.709]} />
            <mesh geometry={nodes.Geom3D_Différence_3.geometry} material={nodes.Geom3D_Différence_3.material} position={[21.102, 0, 0.709]} />
          </group>
          <mesh geometry={nodes.Geom3D_traversse_bas.geometry} material={nodes.Geom3D_traversse_bas.material} scale={25.4} />
          <mesh geometry={nodes.Geom3D_montant_gauche.geometry} material={nodes.Geom3D_montant_gauche.material} position={[582, 0, 18]} scale={25.4} />
          <mesh geometry={nodes.Geom3D_montant_droit.geometry} material={nodes.Geom3D_montant_droit.material} position={[0, 0, 18]} scale={25.4} />
          <mesh geometry={nodes.Geom3D_traverse_haut.geometry} material={nodes.Geom3D_traverse_haut.material} position={[0, 0, 794]} scale={25.4} />
          <mesh geometry={nodes.Geom3D_fond_arrière.geometry} material={nodes.Geom3D_fond_arrière.material} position={[0, 600, 0]} scale={25.4} />
          <mesh geometry={nodes.Geom3D_étagère_1.geometry} material={nodes.Geom3D_étagère_1.material} position={[18, 0, 406]} scale={25.4} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/meuble.glb')
